name: Docker Hub

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš€ Checkout repo
        uses: actions/checkout@v2

      - name: ğŸ¬ Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: ğŸ¬ Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: ğŸš€ Build and push development image
        run: docker-compose -f docker-compose.yml build && docker-compose -f docker-compose.yml push

      - name: ğŸš€ Build and push production image
        run: docker-compose -f docker-compose.prod.yml build && docker-compose -f docker-compose.prod.yml push

      - name: ğŸš€ Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
